Main/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# import add_friend.urls as add_friend
#import stat_dash.urls as stat_dash
import update_status.urls as update_status
import halaman_profile.urls as halaman_profile
import landing_page.urls as landing_page
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^add-friend/', include(add_friend, namespace='add-friend')),
 #   url(r'^dashboard/', include(stat_dash, namespace='dashboard')),
    url(r'^profile/', include(halaman_profile, namespace='profile')),
    url(r'^update-status/', include(update_status, namespace='update-status')),
    url(r'^landing-page/', include(landing_page, namespace='landing-page')),
    url(r'^$', RedirectView.as_view(url='landing-page/', permanent=True), name='$'),
]

update_status/urls.py
from django.conf.urls import url

from update_status.custom_auth import auth_logout, auth_login
from .views import add_status, index

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', add_status, name='add_status'),
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),
]

templates/partials/footer.html
{% block content %}
<p style="margin-top:10px; text-align: center;">&copy; {{author}}</p>
{% endblock %}

templates/partials/header.html
<style>
    .navbar-brand {
        color: #77bceb !important;
        font-family: "Pacifico", cursive;
        font-size: 20pt;
        text-decoration: none;
        display: inline-block;
        text-align: center;
    }
</style>

<div class="container-fullwidth">
    <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light ">
        <a class="navbar-brand" href="/landing-page/">Lingin</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse navbar-right" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/update-status/">Status</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/profile/">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'update-status:auth_logout'%}" style="background-color: #c43238; color: #edecd6; border-radius: 25% ">Logout</a>
                </li>
            </ul>
        </div>
    </nav>
</div>