Main/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# import add_friend.urls as add_friend
#import stat_dash.urls as stat_dash
import update_status.urls as update_status
import halaman_profile.urls as halaman_profile
import landing_page.urls as landing_page
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^add-friend/', include(add_friend, namespace='add-friend')),
 #   url(r'^dashboard/', include(stat_dash, namespace='dashboard')),
    url(r'^profile/', include(halaman_profile, namespace='profile')),
    url(r'^update-status/', include(update_status, namespace='update-status')),
    url(r'^landing-page/', include(landing_page, namespace='landing-page')),
    url(r'^$', RedirectView.as_view(url='landing-page/', permanent=True), name='$'),
]

halaman_profile/urls.py
from django.conf.urls import url
from .views import index, edit_profile

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^edit_profile/$', edit_profile, name='edit_profile'),
]

update_status/urls.py
from django.conf.urls import url

from update_status.custom_auth import auth_logout, auth_login
from .views import add_status, index

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', add_status, name='add_status'),
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),
]

halaman_profile/models.py
# Create your models here.
from django.db import models


class Profile(models.Model):
    kode_identitas = models.CharField('Kode Identitas', max_length=20, primary_key=True)
    name = models.CharField(max_length=30, default='Kosong')
    link = models.URLField('Profile LinkedIn', default='Kosong')
    email = models.EmailField('Email', default='Kosong')


class Expertise(models.Model):
    user = models.ForeignKey(Profile)
    expert = models.CharField('Keahlian', max_length=27)


class Profile_linkedin(models.Model):
    kode_identitas = models.CharField('Kode Identitas', max_length=20, primary_key=True)
    firstName = models.CharField('Nama Depan', max_length=225)
    lastName = models.CharField('Nama Belakang', max_length=225)
    imageUrl = models.URLField('Foto')
    email = models.EmailField('Email', default='Kosong')
    profileUrl = models.URLField('Profile LinkedIn', default='Kosong')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

halaman_profile/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
    attrs = {
        'class': 'form-control'
    }

    message = forms.CharField(label='', widget=forms.Textarea(attrs=attrs), required=True, max_length=300)

halaman_profile/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from .models import Profile, Expertise, Profile_linkedin
from update_status.views import response as r, create_new_user
from update_status.models import Account, Status
from update_status.forms import Status_Form
from .api_riwayat import get_riwayat

response = {'status_form': Status_Form}


def index(request):
    if r['logged_in']:
        response['author'] = r['author']
        response['name'] = Profile.name
        response['email'] = Profile.email
        response['expertise'] = Expertise.expert
        response['npm'] = Profile.kode_identitas
        response['riwayat'] = get_riwayat().json()

        kode_identitas = request.session['kode_identitas']
        if (kode_identitas not in Account.objects.filter(kode_identitas=kode_identitas)):
            create_new_user(request)

        response['latestStatus'] =''
        response['latestStatusDate'] = ''
        response['jumlahAllStatus'] = 0
        response['name'] = Account.objects.get(kode_identitas=kode_identitas).nama
        allStatus = Status.objects.filter(account=Account.objects.get(kode_identitas=kode_identitas))
        response['allStatus'] = allStatus
        response['jumlahAllStatus'] = allStatus.count()
        response['latestStatus'] = allStatus.order_by('-created_date')[0].message if len(allStatus) > 0 else 'No message'
        response['latestStatusDate'] = allStatus.order_by('-created_date')[0].created_date if len(allStatus) > 0 else 'No message'

        return render(request, 'profile.html', response)
    else:
        return HttpResponseRedirect('/update-status/')

def edit_profile(request):
    if 'user_login' in request.session:
        response['name'] = Profile.name
        html = 'edit_profile.html'
        return render(request, html, response)

def save_to_database(request):
    if(request.method == 'POST'):
        firstName = request.POST['firstName']
        lastName = request.POST['lastName']
        imageUrl = request.POST['imageUrl']
        email = request.POST['email']
        profileUrl = request.POST['profileUrl']
        kode_identitas = request.session['kode_identitas']
        exist = Profile_linkedin.objects.filter(kode_identitas=kode_identitas).exists()
        if not exist:
            user = Profile_linkedin(firstName=firstName, lastName=lastName, imageUrl=imageUrl, email=email, profileUrl=profileUrl, kode_identitas=kode_identitas)
            user.save()
        return JsonResponse({'save':'ok'})

halaman_profile/templates/tables/detail_profile.html
<table>
    <tbody>
        <tr>
            <td style="width: 169.2px;">Username</td>
            <td style="width: 356.8px;">{{ name }}</td>
        </tr>
        <tr>
            <td style="width: 169.2px;">NPM</td>
            <td style="width: 356.8px;">{{ npm }}</td>
        </tr>
        <tr>
            <td style="width: 169.2px;">Expertise</td>
            <td style="width: 356.8px;">{{ expert }}
        </tr>
        <tr>
            </td>
            <td style="width: 169.2px;">Profile Linkedin</td>
            <td style="width: 356.8px;">{{ link }}</td>
        </tr>
        <tr>
            <td style="width: 169.2px;">Email</td>
            <td style="width: 356.8px;">{{ email }}</td>
        </tr>
        <a href="{% url 'profile:edit_profile' %}" class="button">Edit Profile </a>

    </tbody>
</table>

halaman_profile/templates/tables/riwayat.html
<div class="panel panel-info">
    <div class="panel-heading">
        <h1> Riwayat Mata Kuliah </h1>
        <h3> Mata Kuliah Selesai : {{ riwayat | length}} </h5>
        <div class="exp" style="text-align: right">
            <p style="font-size: 14pt">Hide Nilai</p>
            <label class="switch">
                <input type="checkbox" id="check">
                <span class="slider round"> </span>
            </label> 
        </div>
             
    </div>

    <div class="panel-body">
        <table class="table" id="table-riwayat">
            <thead>
                <th> No</th>
                <th> Nama Mata Kuliah</th>
                <th> Kode Mata Kuliah</th>
                <th> Jlh. SKS</th>
                <th> Nilai</th>
            </thead>
            <tbody>
                {% for matkul in riwayat %}
                <tr>
                    <td> {{ forloop.counter }}</td>
                    <td> {{ matkul.kelas.nm_mk_cl.nm_mk }}</td>
                    <td> {{ matkul.kd_mk }}</td>
                    <td> {{ matkul.kelas.nm_mk_cl.jml_sks }}</td>
                    <td class="riwayat-nilai"> {{ matkul.nilai }} </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<script>
    $(function() {
        $('#check').change(function() {
            $('.riwayat-nilai').toggle()
        })
    })
</script>

halaman_profile/templates/tables/status.html
<div class="flex">
    {% for i in allStatus reversed %}
        <div class="flex-item">
            <div class="list-status-photo-status">
                <img class="avatar_image" id="status-photo"
                        src="https://vignette2.wikia.nocookie.net/naruto/images/5/50/Team_Kakashi.png/revision/latest?cb=20161219035928">
            </div>
            <div class="list-status">
                <b class="author_name"> {{ i.name }} </b>
                <p class="status_message"> {{ i.message }} </p>
                <p class="created_time"> {{ i.created_date }} </p>
            </div>
        </div>
        <br>
    {% endfor %}
</div>
<div>
    <form id="form" method="POST" action="{% url 'update-status:add_status' %}">
        {% csrf_token %}
        {{ status_form }}
        <br>
        <button type="submit" class="btn btn-default"><span>Post</span></button>
    </form>
</div>
<script type="application/javascript">
    $(".to-do-list-delete-button").click(function () {
        var id = $(this).data('id');
        location.href = "delete_status/" + id;
    });
</script>