Main/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# import add_friend.urls as add_friend
#import stat_dash.urls as stat_dash
import update_status.urls as update_status
import halaman_profile.urls as halaman_profile
import landing_page.urls as landing_page
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^add-friend/', include(add_friend, namespace='add-friend')),
 #   url(r'^dashboard/', include(stat_dash, namespace='dashboard')),
    url(r'^profile/', include(halaman_profile, namespace='profile')),
    url(r'^update-status/', include(update_status, namespace='update-status')),
    url(r'^landing-page/', include(landing_page, namespace='landing-page')),
    url(r'^$', RedirectView.as_view(url='landing-page/', permanent=True), name='$'),
]

update_status/urls.py
from django.conf.urls import url

from update_status.custom_auth import auth_logout, auth_login
from .views import add_status, index

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', add_status, name='add_status'),
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),
]

update_status/models.py
from django.db import models


class Account(models.Model):
    kode_identitas = models.CharField('Kode Identitas', max_length=20, primary_key=True, )
    nama = models.CharField(max_length=200, default="NULL")
    created_at = models.DateTimeField(auto_now_add=True)


class Status(models.Model):
    account = models.ForeignKey(Account)
    name = models.CharField(max_length=27)
    message = models.TextField(max_length=300)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message

update_status/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
    attrs = {
        'class': 'form-control'
    }

    message = forms.CharField(label='', widget=forms.Textarea(attrs=attrs), required=True, max_length=300)

update_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Status_Form
from .models import Status, Account
from django.utils import timezone

# Create your views here.
response = {'author': 'Kelompok 7 PPW-F', 'status_form': Status_Form, 'logged_in': False}


def index(request):
    if 'user_login' in request.session:
        html = 'update_status.html'
        kode_identitas = request.session['kode_identitas']
        if (kode_identitas not in Account.objects.filter(kode_identitas=kode_identitas)):
            create_new_user(request)
        response['name'] = Account.objects.get(kode_identitas=kode_identitas).nama
        allStatus = Status.objects.filter(account=Account.objects.get(kode_identitas=kode_identitas))
        response['allStatus'] = allStatus
        response['npm'] = kode_identitas;
    else:
        html = 'login.html'
    return render(request, html, response)


def add_status(request):
    form = Status_Form(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
        response['message'] = request.POST['message']
        kode_identitas = get_data_user(request, 'kode_identitas')
        account = Account.objects.get(kode_identitas=kode_identitas) or None
        if account is not None:
            status = Status(account=account, name=response['name'], message=response['message'])
            status.save()
            allStatus = Status.objects.all()
            response['allStatus'] = allStatus
            html = 'update_status.html'
        return HttpResponseRedirect('/update-status/')
    else:
        return HttpResponseRedirect('/update-status/')



def get_data_user(request, tipe):
    data = None
    if tipe == "user_login" and 'user_login' in request.session:
        data = request.session['user_login']
    elif tipe == "kode_identitas" and 'kode_identitas' in request.session:
        data = request.session['kode_identitas']

    return data


def create_new_user(request):
    nama = get_data_user(request, 'user_login')
    kode_identitas = get_data_user(request, 'kode_identitas')

    pengguna = Account()
    pengguna.kode_identitas = kode_identitas
    pengguna.nama = nama
    pengguna.created_at = timezone.now()
    pengguna.save()

    return pengguna

update_status/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="row" style="margin: auto">
    <div class="col-md-6 col-md-offset-3" style="margin: auto">
        <div style="margin: auto">
            <div class="judul" style="margin: auto">
                <h1> Halaman Login </h1>
                <p class="text-info"> Gunakan <b> akun SSO </b> untuk login </p>
            </div>
            <form action="{% url 'update-status:auth_login' %}" method="POST">
                {% csrf_token %}
                <p>
                    <label for="username"> Your username </label>
                    <input type="text" id="username" name="username" required>
                </p>
                <p>
                    <label for="password"> Your password </label>
                    <input type="password" id="password" name="password" required>
                </p>
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>
{% endblock %}

update_status/templates/update_status.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block content %}
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'css/update_status.css' %}"/>
    </head>
<body>
    <section name="form">
        <h2 style="margin-top: 100px">Update Status</h2>
        <form id="form" method="POST" action="{% url 'update-status:add_status' %}">
            {% csrf_token %}
            {{ status_form }}
            <br>
            <button type="submit" class="btn btn-default"><span>Post</span></button>
        </form>
        <br>
    </section>

    <section name="status history">
        <div class="flex">
            {% for i in allStatus reversed %}
                <div class="flex-item">
                    <div class="list-status-photo-status">
                        <img class="avatar_image" id="status-photo"
                             src="https://vignette2.wikia.nocookie.net/naruto/images/5/50/Team_Kakashi.png/revision/latest?cb=20161219035928">
                    </div>
                    <div class="list-status">
                        <b class="author_name"> {{ i.name }} </b>
                        <p class="status_message"> {{ i.message }} </p>
                        <p class="created_time"> {{ i.created_date }} </p>
                </div>
                <br>
            {% endfor %}
        </div>
    </section>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript"
            src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
        $(".to-do-list-delete-button").click(function () {
            var id = $(this).data('id');
            location.href = "delete_status/" + id;
        });
    </script>
</body>
{% endblock %}