Main/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# import add_friend.urls as add_friend
#import stat_dash.urls as stat_dash
import update_status.urls as update_status
import halaman_profile.urls as halaman_profile
import landing_page.urls as landing_page
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^add-friend/', include(add_friend, namespace='add-friend')),
 #   url(r'^dashboard/', include(stat_dash, namespace='dashboard')),
    url(r'^profile/', include(halaman_profile, namespace='profile')),
    url(r'^update-status/', include(update_status, namespace='update-status')),
    url(r'^landing-page/', include(landing_page, namespace='landing-page')),
    url(r'^$', RedirectView.as_view(url='landing-page/', permanent=True), name='$'),
]

halaman_profile/urls.py
from django.conf.urls import url
from .views import index, edit_profile

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^edit_profile/$', edit_profile, name='edit_profile'),
]

halaman_profile/models.py
# Create your models here.
from django.db import models


class Profile(models.Model):
    kode_identitas = models.CharField('Kode Identitas', max_length=20, primary_key=True)
    name = models.CharField(max_length=30, default='Kosong')
    link = models.URLField('Profile LinkedIn', default='Kosong')
    email = models.EmailField('Email', default='Kosong')


class Expertise(models.Model):
    user = models.ForeignKey(Profile)
    expert = models.CharField('Keahlian', max_length=27)


class Profile_linkedin(models.Model):
    kode_identitas = models.CharField('Kode Identitas', max_length=20, primary_key=True)
    firstName = models.CharField('Nama Depan', max_length=225)
    lastName = models.CharField('Nama Belakang', max_length=225)
    imageUrl = models.URLField('Foto')
    email = models.EmailField('Email', default='Kosong')
    profileUrl = models.URLField('Profile LinkedIn', default='Kosong')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

halaman_profile/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
    attrs = {
        'class': 'form-control'
    }

    message = forms.CharField(label='', widget=forms.Textarea(attrs=attrs), required=True, max_length=300)

halaman_profile/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from .models import Profile, Expertise, Profile_linkedin
from update_status.views import response as r, create_new_user
from update_status.models import Account, Status
from update_status.forms import Status_Form
from .api_riwayat import get_riwayat

response = {'status_form': Status_Form}


def index(request):
    if r['logged_in']:
        response['author'] = r['author']
        response['name'] = Profile.name
        response['email'] = Profile.email
        response['expertise'] = Expertise.expert
        response['npm'] = Profile.kode_identitas
        response['riwayat'] = get_riwayat().json()

        kode_identitas = request.session['kode_identitas']
        if (kode_identitas not in Account.objects.filter(kode_identitas=kode_identitas)):
            create_new_user(request)

        response['latestStatus'] =''
        response['latestStatusDate'] = ''
        response['jumlahAllStatus'] = 0
        response['name'] = Account.objects.get(kode_identitas=kode_identitas).nama
        allStatus = Status.objects.filter(account=Account.objects.get(kode_identitas=kode_identitas))
        response['allStatus'] = allStatus
        response['jumlahAllStatus'] = allStatus.count()
        response['latestStatus'] = allStatus.order_by('-created_date')[0].message if len(allStatus) > 0 else 'No message'
        response['latestStatusDate'] = allStatus.order_by('-created_date')[0].created_date if len(allStatus) > 0 else 'No message'

        return render(request, 'profile.html', response)
    else:
        return HttpResponseRedirect('/update-status/')

def edit_profile(request):
    if 'user_login' in request.session:
        response['name'] = Profile.name
        html = 'edit_profile.html'
        return render(request, html, response)

def save_to_database(request):
    if(request.method == 'POST'):
        firstName = request.POST['firstName']
        lastName = request.POST['lastName']
        imageUrl = request.POST['imageUrl']
        email = request.POST['email']
        profileUrl = request.POST['profileUrl']
        kode_identitas = request.session['kode_identitas']
        exist = Profile_linkedin.objects.filter(kode_identitas=kode_identitas).exists()
        if not exist:
            user = Profile_linkedin(firstName=firstName, lastName=lastName, imageUrl=imageUrl, email=email, profileUrl=profileUrl, kode_identitas=kode_identitas)
            user.save()
        return JsonResponse({'save':'ok'})

halaman_profile/templates/edit_profile.html
{% extends "base.html" %}
{% load staticfiles %} 
{% load static %} 
{% block content %} 
<!DOCTYPE html>
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript">
    // Setup an event listener to make an API call once auth is complete
    function onLinkedInLoad() {
        IN.Event.on(IN, "auth", getProfileData);
    }

    function displayAdmin(data){
      console.log(data)


    }
    // Use the API call wrapper to request the member's profile data
    function getProfileData() {
    IN.API.Profile("me").fields("id", "first-name", "last-name", "headline", "location", "picture-url", "public-profile-url", "email-address").result(displayProfileData).error(onError);
    }
    //Handle the successful return from the API call
    function displayProfileData(data){
        console.log(data.values[0]);
        var obj = JSON.stringify(data.values[0])
        sessionStorage.setItem("data", obj);

        $('.profile-picture').html(
         '<img class="cover" src="'+ data.values[0].pictureUrl + '"/>'
        );

        var user = data.values[0];
        document.getElementById("name").innerHTML = user.firstName+' '+user.lastName;
        document.getElementById("email").innerHTML = user.emailAddress;
        document.getElementById("link").innerHTML = user.publicProfileUrl;

    }
    // Handle an error response from the API call
    function onError(error) {
        console.log(error);
    }
    // Destroy the session of linkedin
    function logout(){
        IN.User.logout(removeProfileData);
    }
    // Remove profile data from page
    function removeProfileData(){
        document.getElementById('profileData').remove();
    }
    function saveLinkedIn(){
      console.log("success");
      var data = sessionStorage.getItem("data");
      var obj = JSON.parse(data);
      insertDatabase(obj.firstName,obj.lastName,obj.pictureUrl,obj.emailAddress,obj.publicProfileUrl);
    }
        var insertDatabase = function(firstName,lastName,imageUrl,email,profileUrl) {
        $.ajax({
            method: "POST",
            url: 'http://localhost:8000/page_profile/edit_profile',
            data: {
              firstName: firstName,
              lastName: lastName,
              imageUrl: imageUrl,
              email: email,
              profileUrl: profileUrl
            },
            success : function (user) {
                console.log(user);
            },
            error : function (error) {
                console.log(error);
            }
        });
    };

</script>
</head>

<body>
<div class="container">
  <div class="judul">
      <div class="profile-picture">
        <img src="{{Profile_linkedin.profileUrl}}" alt="3x4"/>
      </div>
      <p align="center" style="font-size: 15px;">
          <strong> NPM {{kode_identitas}} </strong>
      </p>
      <p style="float: right;">
          <a class="btn btn-primary" onclick="saveLinkedIn()" > Simpan </a> |
          <a href="{% url 'update-status:index' %}" class="btn btn-warning" > Keluar </a>
      </p><br><br>
  </div>
    <!-- sign in with linkedin button -->
  <script type="in/Login"></script>
  <div id="profileData" style=" font-size: 15px;">
  	<a href="javascript:void(0)" onclick="logout()">Logout</a>

      <div id="picture"></div>
      <div class="info">
        <h5 style=" font-size: 20px;"> Data Pribadi </h5>
        <p id="name"></p>
        <p id="email"></p>
        <p id="link"></p>
      </div>
  </div><br>
  <div class="isi">
    <div class ="keahlian">
      <h5 style=" font-size: 20px;"> Keahlian </h5>
        <select>
          <option value="java">Java</option>
          <option value="python">Python</option>
          <option value="c#">C#</option>
          <option value="c++">C++</option>
        </select>
      <strong style=" font-size: 15px;"> Level </strong>
        <select>
          <option value="beginner">Beginner</option>
          <option value="intermediate">Intermediate</option>
          <option value="advanced#">Advanced</option>
          <option value="expert">Expert</option>
          <option value="legend">Legend</option>
        </select>
    </div><br>
      <h5 style=" font-size: 20px;"> Tampilkan Nilai </h5>
        <form action="">
          <div>
            <input type="radio" name="nilai" value="iya"> Ya <br>
            <input type="radio" name="nilai" value="tidak"> Tidak <br>
          </div>
        </form>
  </div>
</div>
</body>
</html>


<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">

{% endblock %}

halaman_profile/templates/profile.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
{% load static %}
<!-- Link css dan bootstrap tambahan -->
<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/update_status.css' %}"/>

<h1 style="text-align: center;"> Selamat Datang! {{author}}</h1>
<div style="text-align: center;">
    <img class="img-circle" style="border-radius: 50%; height: 200px; width: 200px" src="https://vignette2.wikia.nocookie.net/naruto/images/5/50/Team_Kakashi.png/revision/latest?cb=20161219035928"/>
</div>
</hr>
<section>
    <h2 style="font-weight: bold;" align="center"> Profile {{name}}</h2>
    <div align="center">
        <p style="font-size: 40pt"> {{jumlahAllStatus}} </p>    
        <p>Jumlah status</p>
        <p style="font-size: 28pt">Status terbaru : {{latestStatus}}</p>
        <p style="font-size: 14pt">On : {{latestStatusDate}}</p>
    </div>
</section>
<!-- sign in with linkedin button -->
<script type="in/Login"></script>
</hr>
<div>
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active col-sm-4">
                <a href="#detail_profile" aria-controls="home" role="tab" data-toggle="tab"> Profile </a>
            </li>
            <li role="presentation" class="col-sm-4">
                <a href="#riwayat" aria-controls="settings" role="tab" data-toggle="tab"> Riwayat </a>
            </li>
            <li role="presentation" class="col-sm-4">
                <a href="#status" aria-controls="settings" role="tab" data-toggle="tab"> Status </a>
            </li>
        </ul>
    <br>
    <!-- Tab paness -->
    <div class="tab-content">
            <div role="tabpanel" class="tab-pane fade in active" id="detail_profile">
                {% include 'tables/detail_profile.html' %}
            </div>
            <div role="tabpanel" class="tab-pane fade" id="riwayat">
                {% include 'tables/riwayat.html' %}
            </div>
            <div role="tabpanel" class="tab-pane fade" id="status">
                {% include 'tables/status.html' %}
            </div>
        </div>

    </hr>
</div>
<!-- Script buat handle active tab issues -->
<script>
        $(document).ready(function(){
            $('.nav li').click(function(event){
                //remove all pre-existing active classes
                $('.active').removeClass('active');
        
                //add the active class to the link we clicked
                $(this).addClass('active');
        
                //Load the content
                //e.g.
                //load the page that the link was pointing to
                //$('#content').load($(this).find(a).attr('href'));      
        
                event.preventDefault();
            });
        });
        </script>
        
{% endblock %}